# Generated by Django 6.0.1 on 2026-02-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="discounted_rate",
            new_name="discounted_price",
        ),
    ]
